#!/bin/bash

youtube_time() {
    startTime="$1"
    endTime="$2"
    outputFile="$3"
    youtubeUrl="$4"
    youtube-dl --quiet --no-warnings --output "temp_video.mp4" "$youtubeUrl"

    ffmpeg -i "temp_video.mp4" -ss "$startTime" -to "$endTime" -c:v copy -c:a copy "$outputFile"

    rm "temp_video.mp4"
}

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 <startTime> <endTime> <outputFile> <youtubeUrl>"
    exit 1
fi

youtube_time "$1" "$2" "$3" "$4"